Spring:
  application:
    name: Blog_App

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9090

app:
  base-url: /api/v1
  client:
    origin: ${CLIENT_ORIGIN:http://localhost:5173}
  security:
    token-validity:
      access-validity: 3600
      refresh-validity: 3600
    secret: ${SECURITY_SECRET};
  domain:
    name: ${DOMAIN_NAME}
    secure: ${DOMAIN_SECURE:false}
    same-site: ${DOMAIN_SAME_SITE:Lax}